### ISSUE TITLE
Is there any support for async data?

### ISSUE THREAD

**Issue by lsunsi** [UniversalAvenue/react-compose#2]
For example if I want to pass down data obtained from an http request.
or am I thinking something wrong?

**Comment by danielwerthen** [comment]
You would most likely want to handle async data in a separate layer, like Flux for example. You could also manage it via a stateful React component and update the state when the request has been fulfilled. 

Consider the composed react components as stateless and pure. They in turn can expose properties in which you can pass down any kind of data just fine.

Is that making it any clearer? :-)

**Comment by danielwerthen** [comment]
Will close this for now, let me know if I can help you figuring it out @lsunsi
