### ISSUE TITLE
Import only functions you need from lodash

### ISSUE THREAD

**Issue by pke** [UniversalAvenue/react-compose#4]
Please import only functions you really need from lodash. Generalized imports like `_` blow bundle sizes up.

Beside, double check that ES6 can't deliver what lodash was once good for. See here for a reference:
https://github.com/cht8687/You-Dont-Need-Lodash-Underscore

**Comment by rofrischmann** [comment]
You might want to check out [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) which transforms all your imports while transpiling. e.g.
```javascript
import _ from 'lodash'
_.merge({}, {foo: 'bar'})
```
gets transformed to the ES5 equivalent of:
```javascript
import merge from 'lodash/merge'
_.merge({}, {foo: 'bar'})
```

**Comment by danielwerthen** [comment]
Thanks for the input, this was really about time :-)

babel-plugin-lodash seems to be working very nicely!

**Comment by pke** [comment]
Very good. Thanks!

**Comment by woshifan1989** [comment]
Very good. Thanks!

**Comment by Ninjette** [comment]
import debounce from 'lodash/debounce';

$(window).on('resize', debounce(yourFunction, 600, true)});

**Comment by shikhaBasra** [comment]
`import merge from 'lodash/merge'`

the above code gives error in angular 4. 

Module '"d:/test/node_modules/@types/lodash/merge"' resolves to a non-module entity and cannot be imported using this construct.
module "d:/test/node_modules/@types/lodash/merge"

**Comment by alaricd** [comment]
https://github.com/you-dont-need/You-Dont-Know-Lodash-Underscore
